# Generated by Django 5.1.3 on 2024-12-10 12:59

import datetime
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithAccount',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('birthday', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today)], verbose_name='Дата рождения')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('mail', models.EmailField(max_length=100, verbose_name='Почта')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('language_preference', models.CharField(default='Русский', max_length=100, verbose_name='Предпочтительный язык')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('pronouns', models.CharField(max_length=10, null=True, verbose_name='Местоимения')),
                ('social_url', models.URLField(blank=True, null=True, verbose_name='Социальные сети')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['name'],
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Сообщение')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='accounts.userwithaccount', verbose_name='Пользователь, получивший сообщение')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.userwithaccount', verbose_name='Пользователь, отправивший сообщение')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['created_at'],
            },
        ),
    ]
