# Generated by Django 5.1.3 on 2024-12-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_message_options_remove_message_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwithaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userwithaccount',
            name='updated_at',
        ),
    ]
